= Spring REST Docs Sample API
:doctype: book
:toc: left
:toclevels: 4
:source-highlighter: highlightjs
:operation-http-request-title: Example request
:operation-http-response-title: Example response

== Carts

=== Create a cart

operation::carts-create[snippets='http-request,http-response']

=== Get a cart

operation::cart-get[snippets='http-request,http-response,response-fields,links']

=== Add a product to a cart

operation::cart-add-product[snippets='http-request,http-response']

=== Order  a cart

operation::cart-order[snippets='http-request,http-response']


== Products

=== Create a product

operation::products-create[snippets='http-request,http-response,request-fields']

=== Retrieve a product

operation::product-get[snippets='http-request,http-response,response-fields']

=== Retrieve products

operation::products-get[snippets='http-request,request-parameters,http-response,response-fields,links']

=== Update a product

A patch request can be used to partially update a product.

The update can be expressed in `application/json` or `application/json-patch+json`

operation::product-patch[snippets='http-request']

operation::product-patch-json-patch[snippets='http-request']
